before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - main: cmd/nuclei/main.go
    binary: nuclei
    id: nuclei-cli
    env:
      - CGO_ENABLED=0
    goos: [windows,linux,darwin]
    goarch: [amd64,'386',arm,arm64]
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
      - -pgo=auto
    ldflags:
      - -s
      - -w

#- main: cmd/tmc/main.go
#  binary: tmc
#  id: annotate
#
#  env:
#  - CGO_ENABLED=0
#
#  goos: [linux]
#  goarch: [amd64]

archives:
  - format: zip
    id: nuclei
    builds: [nuclei-cli]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256

announce:
  slack:
    enabled: true
    channel: '#release'
    username: GoReleaser
    message_template: 'New Release: {{ .ProjectName }} {{.Tag}} is published! Check it out at {{ .ReleaseURL }}'

  discord:
    enabled: true
    message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'