package main

import (
	"bytes"
	"embed"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"text/template"

	wappalyzer "github.com/projectdiscovery/wappalyzergo"
)

//go:embed seed_headers.txt seed_cookies.txt
var seedFS embed.FS

const fileTemplate = `// Code generated by genignorelists; DO NOT EDIT.
// Run: go run ./pkg/fuzz/component/cmd/genignorelists
// or:  make fuzz-ignorelists
// Optional: -wappalyzer merges cookie/header names from wappalyzergo fingerprints.

package component

// defaultIgnoredHeaderKeys lists headers that must not be fuzzed.
var defaultIgnoredHeaderKeys = map[string]struct{}{
{{- range .Headers}}
	{{printf "%q" .}}: {},
{{- end}}
}

// defaultIgnoredCookieKeys lists cookies that must not be fuzzed.
var defaultIgnoredCookieKeys = map[string]struct{}{
{{- range .Cookies}}
	{{printf "%q" .}}: {},
{{- end}}
}

// defaultIgnoredCookiePrefixes matches cookie patterns ending in "*" (from -wappalyzer).
var defaultIgnoredCookiePrefixes = []string{
{{- range .CookiePrefixes}}
	{{printf "%q" .}},
{{- end}}
}
`

func main() {
	out := flag.String("out", "", "output Go file (default: ../ignorelists.gen.go next to this tool)")
	withWappalyzer := flag.Bool("wappalyzer", false, "merge header/cookie names from wappalyzergo fingerprints")
	flag.Parse()

	outPath := *out
	if outPath == "" {
		_, file, _, ok := runtime.Caller(0)
		if !ok {
			fatalf("could not resolve generator path")
		}
		outPath = filepath.Join(filepath.Dir(file), "..", "ignorelists.gen.go")
	}

	seedHeaders, err := readSeedLines("seed_headers.txt")
	if err != nil {
		fatalf("seed headers: %v", err)
	}
	seedCookies, err := readSeedLines("seed_cookies.txt")
	if err != nil {
		fatalf("seed cookies: %v", err)
	}

	headers := map[string]struct{}{}
	for _, h := range seedHeaders {
		headers[http.CanonicalHeaderKey(h)] = struct{}{}
	}
	cookies := map[string]struct{}{}
	cookiePrefixes := map[string]struct{}{}
	for _, c := range seedCookies {
		addCookieIgnore(cookies, cookiePrefixes, c)
	}

	var fromWappalyzerHeaders, fromWappalyzerCookies int
	if *withWappalyzer {
		wa, err := wappalyzer.New()
		if err != nil {
			fatalf("wappalyzer: %v", err)
		}
		fps := wa.GetFingerprints()
		if fps == nil || fps.Apps == nil {
			fatalf("wappalyzer: empty fingerprints")
		}
		for _, app := range fps.Apps {
			if app == nil {
				continue
			}
			for name := range app.Headers {
				name = strings.TrimSpace(name)
				if name == "" {
					continue
				}
				canon := http.CanonicalHeaderKey(name)
				if canon == "Set-Cookie" {
					continue
				}
				if _, ok := headers[canon]; !ok {
					fromWappalyzerHeaders++
				}
				headers[canon] = struct{}{}
			}
			for name := range app.Cookies {
				beforeCookies, beforePrefixes := len(cookies), len(cookiePrefixes)
				addCookieIgnore(cookies, cookiePrefixes, name)
				if len(cookies) > beforeCookies || len(cookiePrefixes) > beforePrefixes {
					fromWappalyzerCookies++
				}
			}
		}
	}

	headerList := sortedKeys(headers)
	cookieList := sortedKeys(cookies)
	prefixList := sortedKeys(cookiePrefixes)
	sort.Slice(prefixList, func(i, j int) bool {
		if len(prefixList[i]) == len(prefixList[j]) {
			return prefixList[i] < prefixList[j]
		}
		return len(prefixList[i]) > len(prefixList[j])
	})

	var buf bytes.Buffer
	tpl := template.Must(template.New("gen").Parse(fileTemplate))
	if err := tpl.Execute(&buf, map[string][]string{
		"Headers":        headerList,
		"Cookies":        cookieList,
		"CookiePrefixes": prefixList,
	}); err != nil {
		fatalf("template: %v", err)
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fatalf("write %s: %v", outPath, err)
	}

	fmt.Fprintf(os.Stderr, "wrote %s\n", outPath)
	fmt.Fprintf(os.Stderr, "headers: %d (seed %d", len(headerList), len(seedHeaders))
	if *withWappalyzer {
		fmt.Fprintf(os.Stderr, ", +%d wappalyzer", fromWappalyzerHeaders)
	}
	fmt.Fprintf(os.Stderr, ")\n")
	fmt.Fprintf(os.Stderr, "cookies: %d exact, %d prefixes (seed %d", len(cookieList), len(prefixList), len(seedCookies))
	if *withWappalyzer {
		fmt.Fprintf(os.Stderr, ", +%d wappalyzer", fromWappalyzerCookies)
	}
	fmt.Fprintf(os.Stderr, ")\n")
}

func readSeedLines(name string) ([]string, error) {
	bin, err := seedFS.ReadFile(name)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, line := range strings.Split(string(bin), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out, nil
}

func addCookieIgnore(exact, prefixes map[string]struct{}, name string) {
	name = strings.TrimSpace(name)
	if name == "" {
		return
	}
	if strings.HasSuffix(name, "*") {
		prefix := strings.TrimSuffix(name, "*")
		if prefix != "" {
			prefixes[prefix] = struct{}{}
		}
		return
	}
	if strings.Contains(name, "*") {
		return
	}
	exact[name] = struct{}{}
}

func sortedKeys(m map[string]struct{}) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
