package waf

import (
	"regexp"
	"strings"
	"testing"
)

func TestWAFDetection(t *testing.T) {
	detector := NewWafDetector()
	if detector == nil {
		t.Fatal("expected non-nil wafDetector")
	}

	tests := []struct {
		name        string
		content     string
		expectedWAF string
		shouldMatch bool
	}{
		{
			name:        "Cloudflare WAF",
			content:     "Attention Required! | Cloudflare",
			expectedWAF: "cloudflare",
			shouldMatch: true,
		},
		{
			name:        "ModSecurity WAF",
			content:     "This error was generated by Mod_Security",
			expectedWAF: "modsecurity",
			shouldMatch: true,
		},
		{
			name:        "No WAF",
			content:     "Regular response with no WAF signature",
			expectedWAF: "",
			shouldMatch: false,
		},
		{
			name:        "Wordfence WAF",
			content:     "Generated by Wordfence",
			expectedWAF: "wordfence",
			shouldMatch: true,
		},
		{
			name:        "Sucuri WAF",
			content:     "Access Denied - Sucuri Website Firewall",
			expectedWAF: "sucuri",
			shouldMatch: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			waf, matched := detector.DetectWAF(tt.content)
			if matched != tt.shouldMatch {
				t.Errorf("expected match=%v, got match=%v", tt.shouldMatch, matched)
			}
			if matched && waf != tt.expectedWAF {
				t.Errorf("expected WAF=%s, got WAF=%s", tt.expectedWAF, waf)
			}
		})
	}
}

func TestWAFDetectionNilPointerSafety(t *testing.T) {
	tests := []struct {
		name     string
		detector *WafDetector
		content  string
	}{
		{
			name:     "nil detector",
			detector: nil,
			content:  "test content",
		},
		{
			name: "nil regexCache",
			detector: &WafDetector{
				wafs:       make(map[string]waf),
				regexCache: nil,
			},
			content: "test content",
		},
		{
			name: "regexCache with nil regex",
			detector: &WafDetector{
				wafs: make(map[string]waf),
				regexCache: map[string]*regexp.Regexp{
					"test": nil,
				},
			},
			content: "test content",
		},
		{
			name: "empty regexCache",
			detector: &WafDetector{
				wafs:       make(map[string]waf),
				regexCache: make(map[string]*regexp.Regexp),
			},
			content: "test content",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("DetectWAF panicked with nil pointer: %v", r)
				}
			}()

			waf, matched := tt.detector.DetectWAF(tt.content)
			if matched {
				t.Errorf("expected no match for nil pointer case, got match=true, waf=%s", waf)
			}
			if waf != "" {
				t.Errorf("expected empty WAF string for nil pointer case, got waf=%s", waf)
			}
		})
	}
}

func TestBuildLiteralPrefilter(t *testing.T) {
	tests := []struct {
		name           string
		pattern        string
		admitted       []string
		rejected       []string
		wantFilterable bool
	}{
		{
			name:           "literal",
			pattern:        `Attention Required! \\| Cloudflare`,
			admitted:       []string{"prefix Attention Required! | Cloudflare suffix"},
			rejected:       []string{"ordinary response"},
			wantFilterable: true,
		},
		{
			name:           "alternation admits every branch",
			pattern:        `alpha|bravo`,
			admitted:       []string{"alpha", "bravo"},
			rejected:       []string{"charlie"},
			wantFilterable: true,
		},
		{
			name:           "required concatenated child survives optional prefix",
			pattern:        `(?:optional)?required`,
			admitted:       []string{"required", "optionalrequired"},
			rejected:       []string{"optional"},
			wantFilterable: true,
		},
		{
			name:           "concatenation requires every available literal",
			pattern:        `prefix.+suffix`,
			admitted:       []string{"prefix value suffix"},
			rejected:       []string{"prefix only", "suffix only"},
			wantFilterable: true,
		},
		{
			name:           "required repetition",
			pattern:        `(?:needle)+`,
			admitted:       []string{"needle", "needleneedle"},
			rejected:       []string{"haystack"},
			wantFilterable: true,
		},
		{
			name:           "optional-only expression falls back",
			pattern:        `(?:optional)?`,
			wantFilterable: false,
		},
		{
			name:           "case-folded literal",
			pattern:        `(?i)cloudflare`,
			admitted:       []string{"CLOUDFLARE", "CloudFlare"},
			rejected:       []string{"ordinary response"},
			wantFilterable: true,
		},
		{
			name:           "case-fold uses unicode simple fold semantics",
			pattern:        `(?i)kelvin σ`,
			admitted:       []string{"KELVIN ς", "Kelvin Σ"},
			rejected:       []string{"ordinary response"},
			wantFilterable: true,
		},
		{
			name:           "replacement rune falls back for invalid UTF-8 parity",
			pattern:        "�",
			wantFilterable: false,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			prefilter, ok := buildLiteralPrefilter(test.pattern)
			if ok != test.wantFilterable {
				t.Fatalf("buildLiteralPrefilter(%q) filterable = %t, want %t", test.pattern, ok, test.wantFilterable)
			}
			if !ok {
				return
			}
			for _, input := range test.admitted {
				if !prefilter.allows(input) {
					t.Errorf("prefilter rejected possible match %q", input)
				}
			}
			for _, input := range test.rejected {
				if prefilter.allows(input) {
					t.Errorf("prefilter admitted impossible match %q", input)
				}
			}
		})
	}
}

func TestLiteralPrefilterNeverRejectsProductionRegexMatches(t *testing.T) {
	detector := NewWafDetector()
	inputs := []string{
		"Attention Required! | Cloudflare",
		"This error was generated by Mod_Security",
		"Generated by Wordfence",
		"Access Denied - Sucuri Website Firewall",
		"Server: WatchGuard",
		string([]byte{0xff, 0xfe, 'x'}),
	}

	for id, expression := range detector.wafs {
		compiled := detector.regexCache[id]
		prefilter, filterable := detector.prefilterCache[id]
		for _, input := range inputs {
			if compiled != nil && compiled.MatchString(input) && filterable && !prefilter.allows(input) {
				t.Fatalf("prefilter rejected a production regex match: id=%s expression=%q input=%q", id, expression.Regex, input)
			}
		}
	}
}

func TestDetectWAFReportsPrefilterWork(t *testing.T) {
	detector := &WafDetector{
		wafs: map[string]waf{
			"literal":  {Name: "Literal", Regex: `definitely-present`},
			"fallback": {Name: "Fallback", Regex: `(?i)case-folded`},
		},
		regexCache: map[string]*regexp.Regexp{
			"literal":  regexp.MustCompile(`definitely-present`),
			"fallback": regexp.MustCompile(`(?i)case-folded`),
		},
		prefilterCache: make(map[string]literalPrefilter),
	}
	if prefilter, ok := buildLiteralPrefilter(`definitely-present`); ok {
		detector.prefilterCache["literal"] = prefilter
	}
	if prefilter, ok := buildLiteralPrefilter(`(?i)case-folded`); ok {
		detector.prefilterCache["fallback"] = prefilter
	}

	_, matched, stats := detector.DetectWAFWithStats(strings.Repeat("ordinary response ", 1024))
	if matched {
		t.Fatal("unexpected WAF match")
	}
	if stats.PrefilterSkips != 2 {
		t.Fatalf("prefilter skips = %d, want 2", stats.PrefilterSkips)
	}
	if stats.RegexEvaluations != 0 {
		t.Fatalf("regex evaluations = %d, want 0", stats.RegexEvaluations)
	}
}

func FuzzLiteralPrefilterSoundness(f *testing.F) {
	patterns := []string{
		`alpha`,
		`alpha|bravo`,
		`prefix.+suffix`,
		`(?:optional)?required`,
		`(?:one|two)+`,
		`(?s)begin.+end`,
		`(?i)case-folded`,
		"�",
	}
	inputs := [][]byte{
		[]byte("alpha"),
		[]byte("bravo"),
		[]byte("prefix\nvalue\nsuffix"),
		[]byte("required"),
		{0xff},
		{0xff, 'a', 0xfe},
	}
	for _, pattern := range patterns {
		for _, input := range inputs {
			f.Add(pattern, input)
		}
	}

	f.Fuzz(func(t *testing.T, pattern string, input []byte) {
		compiled, err := regexp.Compile(pattern)
		if err != nil {
			return
		}
		prefilter, filterable := buildLiteralPrefilter(pattern)
		if compiled.Match(input) && filterable && !prefilter.allows(string(input)) {
			t.Fatalf("prefilter rejected regex match: pattern=%q input=%q", pattern, input)
		}
	})
}
