// Code generated by sqlc. DO NOT EDIT.

package dbsql

import (
	"database/sql"
	"time"
)

type Issue struct {
	Matchedat     string
	Title         string
	Severity      string
	Createdat     time.Time
	Updatedat     time.Time
	Scansource    string
	Issuestate    string
	Description   string
	Author        string
	Cvss          sql.NullFloat64
	Cwe           []int32
	Labels        []string
	Issuedata     string
	Issuetemplate string
	Templatename  string
	Remediation   sql.NullString
	Hash          string
	ID            int64
	Scanid        int64
}

type Scan struct {
	Name              string
	Status            string
	Scantime          int64
	Hosts             int64
	Scansource        string
	Templates         []string
	Targets           []string
	Config            sql.NullString
	Runnow            sql.NullBool
	Reporting         sql.NullString
	Scheduleoccurence sql.NullString
	Scheduletime      sql.NullString
	ID                int64
}

type Setting struct {
	Settingdata string
	Datatype    string
	Name        string
}

type Target struct {
	ID         int64
	Name       string
	Internalid string
	Filename   string
	Total      int64
	Createdat  time.Time
	Updatedat  time.Time
}

type Template struct {
	ID        int64
	Name      string
	Folder    string
	Path      string
	Contents  string
	Createdat time.Time
	Updatedat time.Time
	Hash      string
}
