// Code generated by sqlc. DO NOT EDIT.

package dbsql

import (
	"database/sql"
	"time"
)

type Issue struct {
	Template         string
	Templateurl      sql.NullString
	Templateid       sql.NullString
	Templatepath     sql.NullString
	Templatename     string
	Author           sql.NullString
	Labels           []string
	Description      string
	Reference        []string
	Severity         string
	Templatemetadata sql.NullString
	Cvss             sql.NullFloat64
	Cwe              []int32
	Cveid            sql.NullString
	Cvssmetrics      sql.NullString
	Remediation      sql.NullString
	Matchername      sql.NullString
	Extractorname    sql.NullString
	Resulttype       string
	Host             string
	Path             sql.NullString
	Matchedat        string
	Extractedresults []string
	Request          sql.NullString
	Response         sql.NullString
	Metadata         sql.NullString
	Ip               sql.NullString
	Interaction      sql.NullString
	Curlcommand      sql.NullString
	Matcherstatus    sql.NullBool
	Title            string
	Createdat        time.Time
	Updatedat        time.Time
	Scansource       string
	Issuestate       string
	Hash             string
	ID               int64
	Scanid           int64
}

type Scan struct {
	Name              string
	Status            string
	Scantime          int64
	Hosts             int64
	Scansource        string
	Templates         []string
	Targets           []string
	Config            sql.NullString
	Runnow            sql.NullBool
	Reporting         sql.NullString
	Scheduleoccurence sql.NullString
	Scheduletime      sql.NullString
	ID                int64
}

type Setting struct {
	Settingdata string
	Datatype    string
	Name        string
}

type Target struct {
	ID         int64
	Name       string
	Internalid string
	Filename   string
	Total      int64
	Createdat  time.Time
	Updatedat  time.Time
}

type Template struct {
	ID        int64
	Name      string
	Folder    string
	Path      string
	Contents  string
	Createdat time.Time
	Updatedat time.Time
	Hash      string
}

type Version struct {
	ID        int32
	Templates string
}
