// Code generated by sqlc. DO NOT EDIT.

package dbsql

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddIssue(ctx context.Context, arg AddIssueParams) (int64, error)
	AddScan(ctx context.Context, arg AddScanParams) (int64, error)
	AddTarget(ctx context.Context, arg AddTargetParams) (int64, error)
	AddTemplate(ctx context.Context, arg AddTemplateParams) (int64, error)
	DeleteIssue(ctx context.Context, id int64) error
	DeleteIssueByScanID(ctx context.Context, scanid int64) error
	DeleteScan(ctx context.Context, id int64) error
	DeleteTarget(ctx context.Context, id int64) error
	DeleteTemplate(ctx context.Context, path string) error
	GetIssue(ctx context.Context, id int64) (GetIssueRow, error)
	GetIssues(ctx context.Context) ([]GetIssuesRow, error)
	GetIssuesMatches(ctx context.Context, scanid int64) ([]GetIssuesMatchesRow, error)
	GetScan(ctx context.Context, id int64) (Scan, error)
	GetScans(ctx context.Context) ([]Scan, error)
	GetScansBySearchKey(ctx context.Context, dollar_1 sql.NullString) ([]Scan, error)
	GetScansForSchedule(ctx context.Context, scheduleoccurence sql.NullString) ([]GetScansForScheduleRow, error)
	GetSettingByName(ctx context.Context, name string) (GetSettingByNameRow, error)
	GetSettings(ctx context.Context) ([]Setting, error)
	GetTarget(ctx context.Context, id int64) (GetTargetRow, error)
	GetTargetByName(ctx context.Context, name string) (GetTargetByNameRow, error)
	GetTargets(ctx context.Context) ([]GetTargetsRow, error)
	GetTargetsForSearch(ctx context.Context, dollar_1 sql.NullString) ([]GetTargetsForSearchRow, error)
	GetTemplateContents(ctx context.Context, path string) (string, error)
	GetTemplates(ctx context.Context) ([]GetTemplatesRow, error)
	GetTemplatesByFolder(ctx context.Context, folder string) ([]GetTemplatesByFolderRow, error)
	GetTemplatesByFolderOne(ctx context.Context, folder string) (GetTemplatesByFolderOneRow, error)
	GetTemplatesBySearchKey(ctx context.Context, dollar_1 sql.NullString) ([]GetTemplatesBySearchKeyRow, error)
	GetTemplatesForScan(ctx context.Context, folder string) ([]GetTemplatesForScanRow, error)
	SetSettings(ctx context.Context, arg SetSettingsParams) error
	UpdateIssue(ctx context.Context, arg UpdateIssueParams) error
	UpdateScanState(ctx context.Context, arg UpdateScanStateParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpdateTargetMetadata(ctx context.Context, arg UpdateTargetMetadataParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
}

var _ Querier = (*Queries)(nil)
