allow-list:
  severity:
    - high
    - critical
deny-list:
  severity: low

# github contains configuration options for github issue tracker
github:
  # base-url is the optional self-hosted github application url
  base-url: https://localhost:8443/github
  # username is the username of the github user
  username: test-username
  # owner is the owner name of the repository for issues.
  owner: test-owner
  # token is the token for github account.
  token: test-token
  # project-name is the name of the repository.
  project-name: test-project
  # issue-label is the label of the created issue type
  issue-label: bug

# gitlab contains configuration options for gitlab issue tracker
gitlab:
  # base-url is the optional self-hosted gitlab application url
  base-url: https://localhost:8443/gitlab
  # username is the username of the gitlab user
  username: test-username
  # token is the token for gitlab account.
  token: test-token
  # project-id is the ID of the repository.
  project-id: 1234
  # issue-label is the label of the created issue type
  issue-label: bug

# jira contains configuration options for jira issue tracker
jira:
  # cloud is the boolean which tells if Jira instance is running in the cloud or on-prem version is used
  cloud: true
  # update-existing is the boolean which tells if the existing, opened issue should be updated or new one should be created
  update-existing: false
  # URL is the jira application url
  url: https://localhost/jira
  # account-id is the account-id of the jira user or username in case of on-prem Jira
  account-id: test-account-id
  # email is the email of the user for jira instance
  email: test@test.com
  # token is the token for jira instance or password in case of on-prem Jira
  token: test-token
  # project-name is the name of the project.
  project-name: test-project-name
  # issue-type is the name of the created issue type
  issue-type: bug

# elasticsearch contains configuration options for elasticsearch exporter
elasticsearch:
  # IP for elasticsearch instance
  ip: 127.0.0.1
  # Port is the port of elasticsearch instance
  port: 9200
  # IndexName is the name of the elasticsearch index
  index-name: nuclei
  # SSL enables ssl for elasticsearch connection
  ssl: false
  # SSLVerification disables SSL verification for elasticsearch
  ssl-verification: false
  # Username for the elasticsearch instance
  username: test
  # Password is the password for elasticsearch instance
  password: test