// Code generated by sqlc. DO NOT EDIT.

package dbsql

import (
	"database/sql"
)

type Issue struct {
	Matchedat     sql.NullString
	Title         sql.NullString
	Severity      sql.NullString
	Createdat     sql.NullTime
	Updatedat     sql.NullTime
	Scansource    sql.NullString
	Issuestate    sql.NullString
	Description   sql.NullString
	Author        sql.NullString
	Cvss          sql.NullFloat64
	Cwe           []int32
	Labels        []string
	Issuedata     sql.NullString
	Issuetemplate sql.NullString
	Remediation   sql.NullString
	Debug         sql.NullString
	ID            int64
	Scanid        sql.NullInt64
}

type Scan struct {
	Name              sql.NullString
	Status            sql.NullString
	Scantime          sql.NullInt64
	Hosts             sql.NullInt64
	Scansource        sql.NullString
	Templates         []string
	Targets           []string
	Config            sql.NullString
	Runnow            sql.NullBool
	Reporting         sql.NullString
	Scheduleoccurence sql.NullString
	Scheduletime      sql.NullString
	ID                int64
}

type Setting struct {
	Settingdata sql.NullString
	Datatype    sql.NullString
	Name        sql.NullString
}

type Target struct {
	ID         int64
	Name       sql.NullString
	Internalid sql.NullString
	Filename   sql.NullString
	Total      sql.NullInt64
	Createdat  sql.NullTime
	Updatedat  sql.NullTime
}

type Template struct {
	ID        int64
	Name      sql.NullString
	Folder    sql.NullString
	Path      string
	Contents  string
	Createdat sql.NullTime
	Updatedat sql.NullTime
	Hash      sql.NullString
}
