name: ♾️ Compatibility Check

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  check:
    if: github.actor == 'dependabot[bot]'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1
      - run: go mod download && go mod verify && go vet ./...
