name: Typos

on:
  pull_request:
  push:

permissions:
  contents: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Spell check
        uses: crate-ci/typos@v1.42.0
